# Generated by Django 2.0 on 2017-12-23 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
                ('variation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_targets', models.IntegerField()),
                ('part_name', models.CharField(max_length=20)),
                ('solution', models.TextField()),
                ('source', models.URLField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desucar.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desucar.Maker'),
        ),
    ]
