# Generated by Django 2.0 on 2017-12-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='variation',
        ),
    ]
