# Generated by Django 2.0 on 2017-12-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0002_remove_car_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='defect',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='variation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desucar.Car'),
        ),
        migrations.AddField(
            model_name='defect',
            name='target',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='desucar.Revision'),
            preserve_default=False,
        ),
    ]
