# Generated by Django 2.0 on 2018-02-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0004_auto_20180122_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='slug',
        ),
    ]
