# Generated by Django 2.0 on 2018-02-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0005_remove_car_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maker',
            name='slug',
        ),
    ]
