# Generated by Django 2.0 on 2018-02-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0008_auto_20180203_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
