# Generated by Django 2.0 on 2018-02-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0009_auto_20180203_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='simple_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
