# Generated by Django 2.0 on 2018-02-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0011_auto_20180203_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='fix_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='fix_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
