# Generated by Django 2.0 on 2018-02-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0012_auto_20180203_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_defects', to='desucar.Car')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialDefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RC', '리콜'), ('FF', '무상수리')], max_length=2)),
                ('n_targets', models.IntegerField()),
                ('part_name', models.CharField(max_length=20)),
                ('solution', models.TextField()),
                ('source', models.URLField(blank=True, null=True)),
                ('fix_start', models.DateField(blank=True, null=True)),
                ('fix_end', models.DateField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_defects', to='desucar.Car')),
            ],
        ),
        migrations.RemoveField(
            model_name='defect',
            name='car',
        ),
        migrations.DeleteModel(
            name='Defect',
        ),
    ]
