# Generated by Django 2.0 on 2018-03-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0016_auto_20180226_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialdefect',
            name='n_targets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
