# Generated by Django 2.0 on 2018-03-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0018_auto_20180312_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDefectPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('posted_at', models.DateField()),
                ('join_required', models.BooleanField()),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='desucar.CommunityDefect')),
            ],
        ),
        migrations.RemoveField(
            model_name='community',
            name='join_required',
        ),
    ]
