# Generated by Django 2.0 on 2018-03-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0020_remove_communitydefect_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydefectpost',
            name='posted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
