# Generated by Django 2.0 on 2018-03-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0021_auto_20180312_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydefectpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
