# Generated by Django 2.0 on 2018-03-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0023_communitydefect_part_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdefect',
            name='make_end',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officialdefect',
            name='make_start',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
    ]
