# Generated by Django 2.0 on 2018-03-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0024_auto_20180326_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='suddenaccelreport',
            name='car_detail',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
