# Generated by Django 2.0 on 2018-03-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0025_suddenaccelreport_car_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialdefect',
            name='make_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='officialdefect',
            name='make_start',
            field=models.DateField(null=True),
        ),
    ]
