# Generated by Django 2.0 on 2018-03-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0026_auto_20180326_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdefect',
            name='make_date_comment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
