# Generated by Django 2.0 on 2018-03-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0027_officialdefect_make_date_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdefect',
            name='car_detail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
