# Generated by Django 2.0 on 2018-03-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0028_officialdefect_car_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydefectpost',
            name='author_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
