# Generated by Django 2.0 on 2018-03-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0029_communitydefectpost_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maker',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
