# Generated by Django 2.0 on 2018-03-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0030_maker_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officialdefect',
            old_name='source',
            new_name='source_url',
        ),
        migrations.AddField(
            model_name='officialdefect',
            name='source_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
