# Generated by Django 2.0 on 2018-03-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0031_auto_20180329_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='n_members',
            field=models.IntegerField(null=True),
        ),
    ]
