# Generated by Django 2.0 on 2018-03-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0032_auto_20180329_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdefect',
            name='n_targets_comment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
