# Generated by Django 2.0 on 2018-05-14 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0034_car_search_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='desucar.Maker'),
        ),
    ]
