# Generated by Django 2.0 on 2018-05-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0036_nhtsadefect'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydefect',
            name='editor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
