# Generated by Django 2.0 on 2018-05-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0037_communitydefect_editor_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='n_registered',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
