# Generated by Django 2.0 on 2018-05-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0038_car_n_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='suddenaccelreport',
            name='report_at_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suddenaccelreport',
            name='report_at_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suddenaccelreport',
            name='report_at_year',
            field=models.IntegerField(default=1970),
            preserve_default=False,
        ),
    ]
