# Generated by Django 2.0 on 2018-05-21 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desucar', '0039_auto_20180517_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitydefect',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitydefectpost',
            name='defect',
        ),
        migrations.AddField(
            model_name='communitydefect',
            name='posts',
            field=models.ManyToManyField(to='desucar.CommunityDefectPost'),
        ),
        migrations.AddField(
            model_name='communitydefectpost',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='desucar.Community'),
        ),
    ]
